name: python

on: [push, pull_request]

env:
  POETRY_VERSION: "1.7.1"
  PYTHON_VERSION: "3.10"

jobs:
  quality:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        job:
          - { nox-session: lint, poetry-groups: "lint" }
          # type_check needs main and test dependencies for inline type annotations.
          - { nox-session: type_check, poetry-groups: "type_check,main,test" }
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry==${POETRY_VERSION}
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: poetry
      - name: Install Nox and group dependencies
        run: poetry install --only nox,${{ matrix.job.poetry-groups }}
      - name: Test with Nox
        run: poetry run nox -s ${{ matrix.job.nox-session }}
  poetry-check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry==${POETRY_VERSION}
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Validate Poetry Configuration and Lockfile Freshness
        run: poetry check --lock